name: Test, build and deploy
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
permissions: read-all

jobs:
  
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
