name: Test, build and deploy
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
permissions: read-all

jobs:
  
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: ${{ secrets.TESTERS_GROUPS }}
          file: build/app/outputs/flutter-apk/app-release.apk

