name: Test, build and deploy
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
permissions: read-all
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository  with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Run flutter doctor
        run: flutter doctor -v
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get all packages and test
        run: flutter pub get

