name: Test, build and deploy
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
permissions: read-all
jobs:
  example:
    name: Example of job
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo This\ is\ my\ first\ Github\ actions\ job 
